scheduler:
  image:
    repository: "rapidsai/rapidsai-core"
    tag: "22.06-cuda11.5-runtime-ubuntu20.04-py3.9"
  env:
  - name: DISABLE_JUPYTER
    value: "true"

worker:
  image:
    repository: "rapidsai/rapidsai-core"
    tag: "22.06-cuda11.5-runtime-ubuntu20.04-py3.9"
  dask_worker: "dask_cuda_worker"
  replicas: 3
  env:
  - name: DISABLE_JUPYTER
    value: "true"
  resources:
    limits:
      cpu: 1
      memory: 3G
      nvidia.com/gpu: 1
    requests:
      cpu: 1
      memory: 3G
      nvidia.com/gpu: 1

jupyter:
  image:
    repository: "rapidsai/rapidsai-core"
    tag: "22.06-cuda11.5-runtime-ubuntu20.04-py3.9"
  # Default password hash for "rapids"
  password: "argon2:$argon2id$v=19$m=10240,t=10,p=8$TBbhubLuX7efZGRKQqIWtw$RG+jCBB2KYF2VQzxkhMNvHNyJU9MzNGTm2Eu2/f7Qpc"
