name: deployment-docs-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - myst-nb
  - myst-parser
  - nbsphinx
  - numpydoc
  - pydata-sphinx-theme>=0.12.0
  - python=3.9
  - pre-commit
  - sphinx
  - sphinx-autobuild
  - sphinx-copybutton
  - sphinx-design
  - sphinxcontrib-mermaid
  - python-frontmatter
